API Url changed
inpercima/mdrza-ranking pull request #11
Opened 2021-09-03 08:52 UTC by alex1702

2021-09-03 20:20 UTC, inpercima requested changes
:+1: Thank you for your improvement.

Interestingly, the call also works, although "mdrza" is appended to the end of the URL. This is defined in the file "mdrza.service.ts" and is a leftover of the usage with php.

To fulfill this pull request, I think the small addition should be removed. Can you do this?

Thank you for your help.

2021-09-06 06:17 UTC, alex1702 commented
Hab es angepasst

2021-09-06 19:10 UTC, inpercima approved these changes

2021-09-06 19:11 UTC, inpercima commented
Hab vielen Dank, so passt es gut zusammen. :)

2021-09-06 19:12 UTC, merged